import Navigation from './components/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EagleSniper Next App',
  description: 'Generated by Eagle Sniper',
}

const navStyles = {
  display: 'flex',
  justifyContent: 'space-evenly',
  padding: '30px',
  listStyleType:'none'

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <Navigation />
        {children}
        </body>
    </html>
  )
}
